# Generated by Django 5.2.7 on 2025-11-20 22:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.TextField(
                        help_text="e.g., youtube-video, instagram-post", unique=True
                    ),
                ),
                (
                    "target_table",
                    models.TextField(
                        help_text="e.g., core_youtubevideo, core_instagrampost"
                    ),
                ),
                (
                    "platform",
                    models.TextField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("instagram", "Instagram"),
                        ],
                        help_text="Social media platform",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this source does",
                    ),
                ),
            ],
            options={
                "ordering": ["platform", "source_type"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "supabase_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("subscription_tier", models.CharField(default="free", max_length=50)),
                ("api_credits", models.IntegerField(default=0)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n8n_execution_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("input", models.JSONField(null=True)),
                (
                    "extraction_prompt",
                    models.TextField(
                        blank=True,
                        default="Extract location information, business mentions, contact details, and other relevant data from social media posts. Adapt to the specific platform and content type.",
                        help_text="Custom prompt for AI extraction",
                    ),
                ),
                (
                    "enable_extraction",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to run LLM extraction on scraped data",
                    ),
                ),
                (
                    "enhanced_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Enhanced extraction prompt generated by n8n workflow",
                        null=True,
                    ),
                ),
                (
                    "scraped",
                    models.JSONField(
                        help_text="Raw scraped data organized by platform: {'instagram': [...], 'tiktok': [...], ...}",
                        null=True,
                    ),
                ),
                (
                    "extracted",
                    models.JSONField(
                        help_text="Processed entities extracted from scraped data",
                        null=True,
                    ),
                ),
                ("output", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("profile_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji or icon for the list",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User List",
                "verbose_name_plural": "User Lists",
            },
        ),
        migrations.CreateModel(
            name="ListRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="core.userlist",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstagramPost",
            fields=[
                (
                    "id",
                    models.TextField(db_column="id", primary_key=True, serialize=False),
                ),
                ("input_inputUrl", models.TextField(db_column="inputUrl")),
                ("type", models.TextField(db_column="type")),
                ("shortCode", models.TextField(db_column="shortCode")),
                ("caption", models.TextField(blank=True, db_column="caption")),
                (
                    "hashtags",
                    models.JSONField(blank=True, db_column="hashtags", default=list),
                ),
                (
                    "mentions",
                    models.JSONField(blank=True, db_column="mentions", default=list),
                ),
                ("url", models.TextField(db_column="url")),
                (
                    "commentsCount",
                    models.PositiveBigIntegerField(
                        db_column="commentsCount", default=0
                    ),
                ),
                (
                    "firstComment",
                    models.TextField(blank=True, db_column="firstComment"),
                ),
                (
                    "latestComments",
                    models.JSONField(
                        blank=True, db_column="latestComments", default=list
                    ),
                ),
                (
                    "dimensionsHeight",
                    models.PositiveIntegerField(db_column="dimensionsHeight"),
                ),
                (
                    "dimensionsWidth",
                    models.PositiveIntegerField(db_column="dimensionsWidth"),
                ),
                ("displayUrl", models.TextField(db_column="displayUrl")),
                (
                    "images",
                    models.JSONField(blank=True, db_column="images", default=list),
                ),
                (
                    "videoUrl",
                    models.TextField(blank=True, db_column="videoUrl", null=True),
                ),
                (
                    "audioUrl",
                    models.TextField(blank=True, db_column="audioUrl", null=True),
                ),
                (
                    "likesCount",
                    models.PositiveBigIntegerField(db_column="likesCount", default=0),
                ),
                (
                    "videoPlayCount",
                    models.PositiveBigIntegerField(
                        blank=True, db_column="videoPlayCount", null=True
                    ),
                ),
                (
                    "igPlayCount",
                    models.PositiveBigIntegerField(
                        blank=True, db_column="igPlayCount", null=True
                    ),
                ),
                (
                    "videoViewCount",
                    models.PositiveBigIntegerField(
                        blank=True, db_column="videoViewCount", null=True
                    ),
                ),
                (
                    "videoDuration",
                    models.FloatField(blank=True, db_column="videoDuration", null=True),
                ),
                ("timestamp", models.DateTimeField(db_column="timestamp")),
                (
                    "ownerFullName",
                    models.TextField(blank=True, db_column="ownerFullName"),
                ),
                ("ownerUsername", models.TextField(db_column="ownerUsername")),
                ("ownerId", models.TextField(db_column="ownerId")),
                ("productType", models.TextField(blank=True, db_column="productType")),
                (
                    "isSponsored",
                    models.BooleanField(db_column="isSponsored", default=False),
                ),
                (
                    "taggedUsers",
                    models.JSONField(blank=True, db_column="taggedUsers", default=list),
                ),
                (
                    "childPosts",
                    models.JSONField(blank=True, db_column="childPosts", default=list),
                ),
                (
                    "musicInfo",
                    models.JSONField(blank=True, db_column="musicInfo", null=True),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_posts",
                        to="core.run",
                    ),
                ),
            ],
            options={
                "db_table": "instagram_posts",
                "indexes": [
                    models.Index(fields=["run"], name="instagram_p_run_id_a9eb7f_idx"),
                    models.Index(
                        fields=["user"], name="instagram_p_user_id_e56ba2_idx"
                    ),
                    models.Index(
                        fields=["run", "-timestamp"],
                        name="instagram_p_run_id_254253_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InstagramComment",
            fields=[
                (
                    "id",
                    models.TextField(db_column="id", primary_key=True, serialize=False),
                ),
                ("postUrl", models.TextField(db_column="postUrl")),
                ("commentUrl", models.TextField(blank=True, db_column="commentUrl")),
                ("text", models.TextField(db_column="text")),
                ("ownerUsername", models.TextField(db_column="ownerUsername")),
                (
                    "ownerProfilePicUrl",
                    models.TextField(blank=True, db_column="ownerProfilePicUrl"),
                ),
                ("timestamp", models.DateTimeField(db_column="timestamp")),
                (
                    "repliesCount",
                    models.PositiveIntegerField(db_column="repliesCount", default=0),
                ),
                (
                    "replies",
                    models.JSONField(blank=True, db_column="replies", default=list),
                ),
                (
                    "likesCount",
                    models.PositiveIntegerField(db_column="likesCount", default=0),
                ),
                (
                    "owner",
                    models.JSONField(blank=True, db_column="owner", default=dict),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_comments",
                        to="core.run",
                    ),
                ),
            ],
            options={
                "db_table": "instagram_comments",
                "indexes": [
                    models.Index(fields=["run"], name="instagram_c_run_id_326c4c_idx"),
                    models.Index(
                        fields=["user"], name="instagram_c_user_id_7c107e_idx"
                    ),
                    models.Index(
                        fields=["postUrl"], name="instagram_c_postUrl_a07cec_idx"
                    ),
                    models.Index(
                        fields=["-timestamp"], name="instagram_c_timesta_b9fa8f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TikTokVideo",
            fields=[
                (
                    "id",
                    models.TextField(db_column="id", primary_key=True, serialize=False),
                ),
                ("text", models.TextField(blank=True, db_column="text")),
                (
                    "textLanguage",
                    models.TextField(blank=True, db_column="textLanguage"),
                ),
                (
                    "createTime",
                    models.BigIntegerField(
                        blank=True, db_column="createTime", null=True
                    ),
                ),
                (
                    "createTimeISO",
                    models.DateTimeField(
                        blank=True, db_column="createTimeISO", null=True
                    ),
                ),
                ("isAd", models.BooleanField(db_column="isAd", default=False)),
                (
                    "authorMeta",
                    models.JSONField(blank=True, db_column="authorMeta", default=dict),
                ),
                (
                    "musicMeta",
                    models.JSONField(blank=True, db_column="musicMeta", default=dict),
                ),
                ("webVideoUrl", models.TextField(db_column="webVideoUrl")),
                (
                    "mediaUrls",
                    models.JSONField(blank=True, db_column="mediaUrls", default=list),
                ),
                (
                    "videoMeta",
                    models.JSONField(blank=True, db_column="videoMeta", default=dict),
                ),
                (
                    "diggCount",
                    models.PositiveBigIntegerField(db_column="diggCount", default=0),
                ),
                (
                    "shareCount",
                    models.PositiveBigIntegerField(db_column="shareCount", default=0),
                ),
                (
                    "playCount",
                    models.PositiveBigIntegerField(db_column="playCount", default=0),
                ),
                (
                    "collectCount",
                    models.PositiveBigIntegerField(db_column="collectCount", default=0),
                ),
                (
                    "commentCount",
                    models.PositiveBigIntegerField(db_column="commentCount", default=0),
                ),
                (
                    "mentions",
                    models.JSONField(blank=True, db_column="mentions", default=list),
                ),
                (
                    "detailedMentions",
                    models.JSONField(
                        blank=True, db_column="detailedMentions", default=list
                    ),
                ),
                (
                    "hashtags",
                    models.JSONField(blank=True, db_column="hashtags", default=list),
                ),
                (
                    "effectStickers",
                    models.JSONField(
                        blank=True, db_column="effectStickers", default=list
                    ),
                ),
                (
                    "isSlideshow",
                    models.BooleanField(db_column="isSlideshow", default=False),
                ),
                ("isPinned", models.BooleanField(db_column="isPinned", default=False)),
                (
                    "isSponsored",
                    models.BooleanField(db_column="isSponsored", default=False),
                ),
                ("input", models.TextField(blank=True, db_column="input")),
                (
                    "fromProfileSection",
                    models.TextField(blank=True, db_column="fromProfileSection"),
                ),
                (
                    "submittedVideoUrl",
                    models.TextField(blank=True, db_column="submittedVideoUrl"),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiktok_videos",
                        to="core.run",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiktok_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tiktok_videos",
                "indexes": [
                    models.Index(fields=["run"], name="tiktok_vide_run_id_d82004_idx"),
                    models.Index(
                        fields=["user"], name="tiktok_vide_user_id_eb6273_idx"
                    ),
                    models.Index(
                        fields=["run", "-createTimeISO"],
                        name="tiktok_vide_run_id_b854ff_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ListColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "column_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                            ("select", "Select"),
                            ("multi_select", "Multi Select"),
                            ("url", "URL"),
                            ("json", "JSON"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this column contains",
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("options", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="core.userlist",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("user_list", "name")},
            },
        ),
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                (
                    "id",
                    models.TextField(db_column="id", primary_key=True, serialize=False),
                ),
                ("title", models.TextField(db_column="title")),
                (
                    "translatedTitle",
                    models.TextField(
                        blank=True, db_column="translatedTitle", null=True
                    ),
                ),
                ("type", models.TextField(db_column="type")),
                ("url", models.TextField(db_column="url")),
                (
                    "thumbnailUrl",
                    models.TextField(blank=True, db_column="thumbnailUrl"),
                ),
                (
                    "viewCount",
                    models.BigIntegerField(
                        blank=True, db_column="viewCount", null=True
                    ),
                ),
                ("date", models.DateTimeField(blank=True, db_column="date", null=True)),
                (
                    "likes",
                    models.BigIntegerField(blank=True, db_column="likes", null=True),
                ),
                ("location", models.TextField(blank=True, db_column="location")),
                ("channelName", models.TextField(db_column="channelName")),
                ("channelUrl", models.TextField(db_column="channelUrl")),
                (
                    "channelUsername",
                    models.TextField(blank=True, db_column="channelUsername"),
                ),
                ("channelId", models.TextField(db_column="channelId")),
                (
                    "numberOfSubscribers",
                    models.BigIntegerField(
                        blank=True, db_column="numberOfSubscribers", null=True
                    ),
                ),
                ("duration", models.TextField(blank=True, db_column="duration")),
                (
                    "commentsCount",
                    models.BigIntegerField(
                        blank=True, db_column="commentsCount", null=True
                    ),
                ),
                ("text", models.TextField(blank=True, db_column="text")),
                (
                    "translatedText",
                    models.TextField(blank=True, db_column="translatedText"),
                ),
                (
                    "descriptionLinks",
                    models.JSONField(
                        blank=True, db_column="descriptionLinks", default=list
                    ),
                ),
                (
                    "subtitles",
                    models.JSONField(blank=True, db_column="subtitles", default=list),
                ),
                (
                    "hashtags",
                    models.JSONField(blank=True, db_column="hashtags", default=list),
                ),
                (
                    "formats",
                    models.JSONField(blank=True, db_column="formats", default=list),
                ),
                (
                    "commentsTurnedOff",
                    models.BooleanField(db_column="commentsTurnedOff", default=False),
                ),
                (
                    "isMembersOnly",
                    models.BooleanField(db_column="isMembersOnly", default=False),
                ),
                (
                    "isMonetized",
                    models.BooleanField(blank=True, db_column="isMonetized", null=True),
                ),
                (
                    "order",
                    models.IntegerField(blank=True, db_column="order", null=True),
                ),
                ("fromYTUrl", models.TextField(blank=True, db_column="fromYTUrl")),
                ("input", models.TextField(blank=True, db_column="input")),
                (
                    "fromChannelListPage",
                    models.TextField(blank=True, db_column="fromChannelListPage"),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_videos",
                        to="core.run",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "youtube_videos",
                "indexes": [
                    models.Index(fields=["run"], name="youtube_vid_run_id_0a01fd_idx"),
                    models.Index(
                        fields=["user"], name="youtube_vid_user_id_e8ecdd_idx"
                    ),
                ],
            },
        ),
    ]
