# Generated by Django 5.2.7 on 2025-11-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="instagramcomment",
            new_name="data_instag_run_id_b28107_idx",
            old_name="instagram_c_run_id_326c4c_idx",
        ),
        migrations.RenameIndex(
            model_name="instagramcomment",
            new_name="data_instag_user_id_1aba4d_idx",
            old_name="instagram_c_user_id_7c107e_idx",
        ),
        migrations.RenameIndex(
            model_name="instagramcomment",
            new_name="data_instag_postUrl_c2f075_idx",
            old_name="instagram_c_postUrl_a07cec_idx",
        ),
        migrations.RenameIndex(
            model_name="instagramcomment",
            new_name="data_instag_timesta_577df7_idx",
            old_name="instagram_c_timesta_b9fa8f_idx",
        ),
        migrations.RenameIndex(
            model_name="instagrampost",
            new_name="data_instag_run_id_4cf692_idx",
            old_name="instagram_p_run_id_a9eb7f_idx",
        ),
        migrations.RenameIndex(
            model_name="instagrampost",
            new_name="data_instag_user_id_5688a0_idx",
            old_name="instagram_p_user_id_e56ba2_idx",
        ),
        migrations.RenameIndex(
            model_name="instagrampost",
            new_name="data_instag_run_id_5c458f_idx",
            old_name="instagram_p_run_id_254253_idx",
        ),
        migrations.RenameIndex(
            model_name="tiktokvideo",
            new_name="data_tiktok_run_id_a973ab_idx",
            old_name="tiktok_vide_run_id_d82004_idx",
        ),
        migrations.RenameIndex(
            model_name="tiktokvideo",
            new_name="data_tiktok_user_id_aae0d0_idx",
            old_name="tiktok_vide_user_id_eb6273_idx",
        ),
        migrations.RenameIndex(
            model_name="tiktokvideo",
            new_name="data_tiktok_run_id_a12470_idx",
            old_name="tiktok_vide_run_id_b854ff_idx",
        ),
        migrations.RenameIndex(
            model_name="youtubevideo",
            new_name="data_youtub_run_id_5a200f_idx",
            old_name="youtube_vid_run_id_0a01fd_idx",
        ),
        migrations.RenameIndex(
            model_name="youtubevideo",
            new_name="data_youtub_user_id_0d891a_idx",
            old_name="youtube_vid_user_id_e8ecdd_idx",
        ),
        migrations.AlterModelTable(
            name="instagramcomment",
            table="data_instagram_comments",
        ),
        migrations.AlterModelTable(
            name="instagrampost",
            table="data_instagram_posts",
        ),
        migrations.AlterModelTable(
            name="tiktokvideo",
            table="data_tiktok_videos",
        ),
        migrations.AlterModelTable(
            name="youtubevideo",
            table="data_youtube_videos",
        ),
    ]
