# Generated by Django 5.2.7 on 2025-10-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_location_post_url_alter_location_profile_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="source_profile",
        ),
        migrations.AddField(
            model_name="location",
            name="run_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
