# Generated by Django 5.2.7 on 2025-11-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_tables_with_data_prefix"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialProfile",
        ),
    ]
