# Generated by Django 5.2.7 on 2025-10-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_run_n8n_execution_id_alter_run_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='n8n_execution_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
