# Generated by Django 5.2.7 on 2025-10-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_location_source_profile_location_run_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="user",
        ),
        migrations.AddField(
            model_name="location",
            name="user_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
