# Generated by Django 5.2.7 on 2025-11-20 23:15

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_socialprofile_model"),
    ]

    operations = [
        # Rename input_inputUrl to inputUrl
        migrations.RenameField(
            model_name='instagrampost',
            old_name='input_inputUrl',
            new_name='inputUrl',
        ),
        # Drop and recreate hashtags column as ArrayField
        migrations.RemoveField(
            model_name='instagrampost',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='hashtags',
            field=ArrayField(
                models.TextField(),
                default=list,
                blank=True,
                db_column='hashtags',
                size=None
            ),
        ),
        # Drop and recreate mentions column as ArrayField
        migrations.RemoveField(
            model_name='instagrampost',
            name='mentions',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='mentions',
            field=ArrayField(
                models.TextField(),
                default=list,
                blank=True,
                db_column='mentions',
                size=None
            ),
        ),
    ]
