# Generated by Django 5.2.7 on 2025-11-21 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_update_instagram_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceOutputMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.TextField(db_index=True)),
                ("source_type", models.TextField(db_index=True)),
                ("output_type", models.TextField(db_index=True)),
                (
                    "display_name",
                    models.TextField(
                        help_text="Human name shown in UI, e.g. 'Instagram Profile Posts'"
                    ),
                ),
                (
                    "field_mappings",
                    models.JSONField(
                        default=dict,
                        help_text="Pretty path → {friendly_name, json_path, type, popular}",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Source Output Mapping",
                "db_table": "source_output_mapping",
                "unique_together": {("platform", "source_type", "output_type")},
            },
        ),
        migrations.CreateModel(
            name="DataLandingZone",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("object_id", models.TextField(blank=True, db_index=True, null=True)),
                (
                    "object_created_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("expires_on", models.DateTimeField(blank=True, null=True)),
                ("source_url", models.TextField(blank=True, null=True)),
                ("data", models.JSONField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_zone_entries",
                        to="core.run",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_zone_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landing_zone_entries",
                        to="core.sourceoutputmapping",
                    ),
                ),
            ],
            options={
                "db_table": "data_landing_zone",
                "indexes": [
                    models.Index(fields=["run"], name="idx_lz_run"),
                    models.Index(
                        fields=["user", "source_mapping", "object_created_at"],
                        name="idx_lz_user_source_date",
                    ),
                    models.Index(
                        fields=["source_mapping", "object_id"], name="idx_lz_object"
                    ),
                ],
            },
        ),
    ]
