# Generated by Django 5.2.7 on 2025-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_run_n8n_execution_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='output',
            field=models.JSONField(null=True),
        ),
    ]
