# Generated by Django 5.2.7 on 2025-10-23 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_run_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedlist',
            name='data_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CuratedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_data', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curated_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curatedlist')),
                ('source_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
