# Generated by Django 5.2.7 on 2025-10-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_curatedlist_data_schema_curateditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='extracted',
            field=models.JSONField(help_text='Processed entities extracted from scraped data', null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='scraped',
            field=models.JSONField(help_text='Raw scraped data from Instagram posts', null=True),
        ),
    ]
