# Generated by Django 5.2.7 on 2025-11-24 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_refactor_source_output_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_id', models.TextField(db_index=True)),
                ('attribute', models.TextField(db_index=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_transit',
            },
        ),
        migrations.RemoveIndex(
            model_name='datalandingzone',
            name='idx_lz_data_gin',
        ),
        migrations.AddField(
            model_name='datatransit',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_entries', to='core.run'),
        ),
        migrations.AddField(
            model_name='datatransit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='datatransit',
            index=models.Index(fields=['run', 'entity_id'], name='idx_transit_run_entity'),
        ),
        migrations.AddIndex(
            model_name='datatransit',
            index=models.Index(fields=['run', 'attribute'], name='idx_transit_run_attr'),
        ),
        migrations.AddConstraint(
            model_name='datatransit',
            constraint=models.UniqueConstraint(fields=('run', 'entity_id', 'attribute'), name='unique_transit_entry'),
        ),
    ]
