# Generated by Django 5.2.7 on 2025-10-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_migrate_output_to_extracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='enable_extraction',
            field=models.BooleanField(default=True, help_text='Whether to run LLM extraction on scraped data'),
        ),
    ]
