# Generated by Django 5.2.7 on 2025-10-24 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_run_enable_extraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatedlist',
            name='user',
        ),
        migrations.AlterField(
            model_name='run',
            name='scraped',
            field=models.JSONField(help_text="Raw scraped data organized by platform: {'instagram': [...], 'tiktok': [...], ...}", null=True),
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User List',
                'verbose_name_plural': 'User Lists',
            },
        ),
        migrations.CreateModel(
            name='ListRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.userlist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('column_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('json', 'JSON')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.userlist')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('user_list', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='CuratedItem',
        ),
        migrations.DeleteModel(
            name='CuratedList',
        ),
    ]
