# Generated by Django 5.2.7 on 2025-10-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_curatedlist_user_alter_run_scraped_userlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcolumn',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listcolumn',
            name='column_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('url', 'URL'), ('json', 'JSON')], default='text', max_length=20),
        ),
    ]
