# Generated by Django 5.2.7 on 2025-10-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_listcolumn_options_alter_listcolumn_column_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcolumn',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of what this column contains'),
        ),
    ]
