# Generated by Django 5.2.7 on 2025-11-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_listcolumn_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='enhanced_prompt',
            field=models.TextField(blank=True, help_text='Enhanced extraction prompt generated by n8n workflow', null=True),
        ),
    ]
