# Generated by Django 5.2.7 on 2025-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_run_enhanced_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='extraction_prompt',
            field=models.TextField(blank=True, default='Extract location information, business mentions, contact details, and other relevant data from social media posts. Adapt to the specific platform and content type.', help_text='Custom prompt for AI extraction'),
        ),
    ]
