# Generated by Django 5.2.7 on 2025-11-09 14:00

import json
from django.db import migrations


def migrate_extraction_prompt_from_input(apps, schema_editor):
    """Move extraction_prompt from input JSON to separate column"""
    Run = apps.get_model('core', 'Run')
    
    for run in Run.objects.all():
        if run.input and not run.extraction_prompt:
            try:
                input_data = json.loads(run.input) if isinstance(run.input, str) else run.input
                if input_data and 'extraction_prompt' in input_data:
                    run.extraction_prompt = input_data['extraction_prompt']
                    run.save(update_fields=['extraction_prompt'])
            except (json.JSONDecodeError, TypeError):
                # Skip if input is not valid JSON
                continue


def reverse_migrate_extraction_prompt(apps, schema_editor):
    """Reverse migration: move extraction_prompt back to input JSON"""
    Run = apps.get_model('core', 'Run')
    
    for run in Run.objects.all():
        if run.extraction_prompt and run.input:
            try:
                input_data = json.loads(run.input) if isinstance(run.input, str) else run.input
                if input_data is not None:
                    input_data['extraction_prompt'] = run.extraction_prompt
                    run.input = json.dumps(input_data)
                    run.save(update_fields=['input'])
            except (json.JSONDecodeError, TypeError):
                # Skip if input is not valid JSON
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_run_extraction_prompt'),
    ]

    operations = [
        migrations.RunPython(
            migrate_extraction_prompt_from_input,
            reverse_migrate_extraction_prompt,
        ),
    ]
