# Generated by Django 5.2.7 on 2025-11-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_supabase_auth_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='icon',
            field=models.CharField(blank=True, default='📋', help_text='Emoji or icon for the list', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='supabase_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
