# Generated by Django 5.2.7 on 2025-11-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_list_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon for the list', max_length=50),
        ),
    ]
