# Generated by Django 5.2.7 on 2025-11-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fix_run_user_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_credits',
            field=models.IntegerField(default=0),
        ),
    ]
