# Generated by Django 5.2.7 on 2025-11-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_user_api_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True, db_index=True)),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('translated_title', models.CharField(max_length=500, blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('channel_id', models.CharField(max_length=50, blank=True, db_index=True)),
                ('channel_name', models.CharField(max_length=255, blank=True)),
                ('channel_username', models.CharField(max_length=100, blank=True)),
                ('channel_url', models.URLField(blank=True)),
                ('subscriber_count', models.BigIntegerField(default=0)),
                ('text_content', models.TextField(blank=True)),
                ('hashtags', models.JSONField(default=list, blank=True)),
                ('tags', models.JSONField(default=list, blank=True)),
                ('language', models.CharField(max_length=10, blank=True)),
                ('category', models.CharField(max_length=100, blank=True)),
                ('is_monetized', models.BooleanField(default=False)),
                ('comments_disabled', models.BooleanField(default=False)),
                ('is_members_only', models.BooleanField(default=False)),
                ('source_type', models.CharField(max_length=20)),
                ('extraction_date', models.DateTimeField(null=True, blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(null=True, blank=True)),
                ('user', models.ForeignKey('core.user', on_delete=models.CASCADE)),
                ('run', models.ForeignKey('core.run', on_delete=models.SET_NULL, null=True, blank=True)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['expires_at'], name='core_youtubevideo_expires_at_idx'),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION set_youtube_expiry()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.expires_at IS NULL THEN
                        NEW.expires_at = NOW() + INTERVAL '7 days';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                
                DROP TRIGGER IF EXISTS youtube_video_expiry_trigger ON core_youtubevideo;
                CREATE TRIGGER youtube_video_expiry_trigger
                    BEFORE INSERT ON core_youtubevideo
                    FOR EACH ROW EXECUTE FUNCTION set_youtube_expiry();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS youtube_video_expiry_trigger ON core_youtubevideo;
                DROP FUNCTION IF EXISTS set_youtube_expiry();
            """,
        ),
    ]