# Generated by Django 5.2.7 on 2025-11-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_add_youtube_video_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='youtube_video',
            field=models.ForeignKey(
                'core.youtubevideo', 
                on_delete=models.SET_NULL, 
                null=True, 
                blank=True,
                related_name='youtube_video'
            ),
        ),
    ]