# Generated by Django 5.2.7 on 2025-11-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_add_youtube_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='subtitles',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="Subtitles data from YouTube video output as array of subtitle objects"
            ),
        ),
    ]