# Generated by Django 5.2.7 on 2025-11-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_youtube_video_subtitles_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listrow',
            options={},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['-published_at']},
        ),
        migrations.RenameIndex(
            model_name='youtubevideo',
            new_name='core_youtub_expires_be0eb0_idx',
            old_name='core_youtubevideo_expires_at_idx',
        ),
        migrations.RemoveField(
            model_name='run',
            name='youtube_video',
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['video_id'], name='core_youtub_video_i_d63169_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['channel_id'], name='core_youtub_channel_5cd540_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['published_at'], name='core_youtub_publish_29223f_idx'),
        ),
    ]
