# Generated by Django 5.2.7 on 2025-11-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_subtitles_field_to_youtube_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listrow',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='youtubevideo',
            name='core_youtub_expires_be0eb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='youtubevideo',
            name='core_youtub_video_i_d63169_idx',
        ),
        migrations.RemoveIndex(
            model_name='youtubevideo',
            name='core_youtub_channel_5cd540_idx',
        ),
        migrations.RemoveIndex(
            model_name='youtubevideo',
            name='core_youtub_publish_29223f_idx',
        ),
    ]
