# Generated by Django 5.2.7 on 2025-11-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_listrow_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='channel_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['video_id'], name='core_youtub_video_i_d63169_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['channel_id'], name='core_youtub_channel_5cd540_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['published_at'], name='core_youtub_publish_29223f_idx'),
        ),
    ]
