# Generated by Django 5.2.7 on 2025-11-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_youtubevideo_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
