# Generated by Django 5.2.7 on 2025-11-20 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_youtubevideo_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TikTokVideo",
            fields=[
                (
                    "tiktok_id",
                    models.CharField(
                        help_text="TikTok video ID",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, help_text="Video caption/description"),
                ),
                (
                    "text_language",
                    models.CharField(
                        blank=True,
                        help_text="Language code (e.g., 'en')",
                        max_length=10,
                    ),
                ),
                ("create_time", models.BigIntegerField(help_text="Unix timestamp")),
                ("create_time_iso", models.DateTimeField(help_text="ISO datetime")),
                ("location_created", models.CharField(blank=True, max_length=100)),
                ("is_ad", models.BooleanField(default=False)),
                ("author_id", models.CharField(blank=True, max_length=50)),
                ("author_name", models.CharField(blank=True, max_length=255)),
                ("author_profile_url", models.URLField(blank=True)),
                ("author_nickname", models.CharField(blank=True, max_length=255)),
                ("author_verified", models.BooleanField(default=False)),
                ("author_signature", models.TextField(blank=True)),
                ("author_bio_link", models.URLField(blank=True)),
                ("author_avatar_url", models.URLField(blank=True)),
                ("author_private_account", models.BooleanField(default=False)),
                ("author_following", models.BigIntegerField(default=0)),
                ("author_friends", models.BigIntegerField(default=0)),
                ("author_fans", models.BigIntegerField(default=0)),
                ("author_heart", models.BigIntegerField(default=0)),
                ("author_video_count", models.BigIntegerField(default=0)),
                ("author_digg", models.BigIntegerField(default=0)),
                ("music_name", models.CharField(blank=True, max_length=255)),
                ("music_author", models.CharField(blank=True, max_length=255)),
                ("music_original", models.BooleanField(default=False)),
                ("music_play_url", models.URLField(blank=True)),
                ("music_cover_url", models.URLField(blank=True)),
                ("music_id", models.CharField(blank=True, max_length=50)),
                ("web_video_url", models.URLField(blank=True)),
                ("video_height", models.PositiveIntegerField(null=True)),
                ("video_width", models.PositiveIntegerField(null=True)),
                ("video_duration", models.PositiveIntegerField(null=True)),
                ("video_cover_url", models.URLField(blank=True)),
                ("video_definition", models.CharField(blank=True, max_length=20)),
                ("video_format", models.CharField(blank=True, max_length=10)),
                ("digg_count", models.BigIntegerField(default=0)),
                ("share_count", models.BigIntegerField(default=0)),
                ("play_count", models.BigIntegerField(default=0)),
                ("collect_count", models.BigIntegerField(default=0)),
                ("comment_count", models.BigIntegerField(default=0)),
                ("mentions", models.JSONField(blank=True, default=list)),
                ("detailed_mentions", models.JSONField(blank=True, default=list)),
                ("hashtags", models.JSONField(blank=True, default=list)),
                ("effect_stickers", models.JSONField(blank=True, default=list)),
                ("is_slideshow", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_sponsored", models.BooleanField(default=False)),
                (
                    "author_meta",
                    models.JSONField(
                        blank=True, help_text="Complete authorMeta object", null=True
                    ),
                ),
                (
                    "music_meta",
                    models.JSONField(
                        blank=True, help_text="Complete musicMeta object", null=True
                    ),
                ),
                (
                    "video_meta",
                    models.JSONField(
                        blank=True, help_text="Complete videoMeta object", null=True
                    ),
                ),
                (
                    "subtitle_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of subtitle link objects",
                    ),
                ),
                ("extraction_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.run",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-create_time_iso"],
                "indexes": [
                    models.Index(fields=["tiktok_id"], name="core_tiktok_video_id_idx"),
                    models.Index(
                        fields=["author_id"], name="core_tiktok_author_id_idx"
                    ),
                    models.Index(
                        fields=["create_time_iso"], name="core_tiktok_create_time_idx"
                    ),
                    models.Index(
                        fields=["user", "create_time_iso"],
                        name="core_tiktok_user_time_idx",
                    ),
                ],
            },
        ),
    ]
