# Generated by Django 5.2.7 on 2025-11-20 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_tiktok_video_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('owner_username', models.CharField(max_length=255)),
                ('owner_profile_pic_url', models.URLField()),
                ('timestamp', models.DateTimeField()),
                ('replies_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('owner', models.JSONField()),
                ('post_url', models.URLField()),
                ('comment_url', models.URLField()),
                ('replies', models.JSONField(default=list)),
                ('extraction_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=255)),
                ('mentioned_user_id', models.CharField(blank=True, max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_pic_url', models.URLField(blank=True)),
                ('extraction_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('short_code', models.CharField(max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.JSONField(default=list)),
                ('mentions', models.JSONField(default=list)),
                ('url', models.URLField()),
                ('comments_count', models.IntegerField(default=0)),
                ('first_comment', models.TextField(blank=True)),
                ('dimensions_height', models.IntegerField()),
                ('dimensions_width', models.IntegerField()),
                ('display_url', models.URLField()),
                ('images', models.JSONField(default=list)),
                ('likes_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('owner_full_name', models.CharField(blank=True, max_length=255)),
                ('owner_username', models.CharField(max_length=255)),
                ('owner_id', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('music_info', models.JSONField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_view_count', models.IntegerField(blank=True, null=True)),
                ('video_play_count', models.IntegerField(blank=True, null=True)),
                ('video_duration', models.FloatField(blank=True, null=True)),
                ('input_url', models.URLField()),
                ('child_posts', models.JSONField(default=list)),
                ('tagged_users', models.JSONField(default=list)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_comments_disabled', models.BooleanField(default=False)),
                ('alt', models.TextField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('ig_play_count', models.IntegerField(blank=True, null=True)),
                ('fb_like_count', models.IntegerField(blank=True, null=True)),
                ('fb_play_count', models.IntegerField(blank=True, null=True)),
                ('reshare_count', models.IntegerField(blank=True, null=True)),
                ('extraction_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
