# Generated by Django 5.2.7 on 2025-11-20 14:05

from django.db import migrations, models


def seed_source_mappings(apps, schema_editor):
    SourceMapping = apps.get_model('core', 'SourceMapping')
    mappings = [
        {'source_type': 'youtube-video', 'target_table': 'core_youtubevideo', 'platform': 'youtube', 'description': 'Individual YouTube videos'},
        {'source_type': 'youtube-channel', 'target_table': 'core_youtubevideo', 'platform': 'youtube', 'description': 'YouTube channel videos'},
        {'source_type': 'youtube-hashtag', 'target_table': 'core_youtubevideo', 'platform': 'youtube', 'description': 'Videos from YouTube hashtag searches'},
        {'source_type': 'youtube-playlist', 'target_table': 'core_youtubevideo', 'platform': 'youtube', 'description': 'Videos from YouTube playlists'},
        {'source_type': 'youtube-search', 'target_table': 'core_youtubevideo', 'platform': 'youtube', 'description': 'Videos from YouTube search queries'},
        {'source_type': 'tiktok-video', 'target_table': 'core_tiktokvideo', 'platform': 'tiktok', 'description': 'Individual TikTok videos'},
        {'source_type': 'tiktok-hashtag', 'target_table': 'core_tiktokvideo', 'platform': 'tiktok', 'description': 'Videos from TikTok hashtag searches'},
        {'source_type': 'tiktok-profile', 'target_table': 'core_tiktokvideo', 'platform': 'tiktok', 'description': 'Videos from TikTok profiles'},
        {'source_type': 'tiktok-search', 'target_table': 'core_tiktokvideo', 'platform': 'tiktok', 'description': 'Videos from TikTok search queries'},
        {'source_type': 'instagram-hashtag', 'target_table': 'core_instagrampost', 'platform': 'instagram', 'description': 'Instagram posts from hashtag searches'},
        {'source_type': 'instagram-post', 'target_table': 'core_instagrampost', 'platform': 'instagram', 'description': 'Individual Instagram posts'},
        {'source_type': 'instagram-post-comments', 'target_table': 'core_instagramcomment', 'platform': 'instagram', 'description': 'Comments on Instagram posts'},
        {'source_type': 'instagram-profile-mentions', 'target_table': 'core_instagrammention', 'platform': 'instagram', 'description': 'Mentions in Instagram posts'},
        {'source_type': 'instagram-profile-posts', 'target_table': 'core_instagrampost', 'platform': 'instagram', 'description': 'Posts from Instagram profiles'},
        {'source_type': 'instagram-profile-reels', 'target_table': 'core_instagrampost', 'platform': 'instagram', 'description': 'Reels from Instagram profiles'},
    ]
    for mapping in mappings:
        SourceMapping.objects.create(**mapping)


def reverse_seed_source_mappings(apps, schema_editor):
    SourceMapping = apps.get_model('core', 'SourceMapping')
    SourceMapping.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_instagramcomment_instagrammention_instagrampost"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        help_text="e.g., youtube-video, instagram-post",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "target_table",
                    models.CharField(
                        help_text="e.g., core_youtubevideo, core_instagrampost",
                        max_length=100,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("instagram", "Instagram"),
                        ],
                        help_text="Social media platform",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this source does",
                    ),
                ),
            ],
            options={
                "ordering": ["platform", "source_type"],
            },
        ),
        migrations.RunPython(seed_source_mappings, reverse_seed_source_mappings),
    ]
