# Generated by Django 5.2.7 on 2025-11-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_sourcemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcomment',
            name='comment_url',
            field=models.URLField(db_column='commentUrl'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='id',
            field=models.BigAutoField(db_column='django_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='instagram_id',
            field=models.CharField(db_column='id', max_length=50),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='likes_count',
            field=models.IntegerField(db_column='likesCount', default=0),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='owner_profile_pic_url',
            field=models.URLField(db_column='ownerProfilePicUrl'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='owner_username',
            field=models.CharField(db_column='ownerUsername', max_length=255),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='post_url',
            field=models.URLField(db_column='postUrl'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='replies_count',
            field=models.IntegerField(db_column='repliesCount', default=0),
        ),
        migrations.AlterField(
            model_name='instagrammention',
            name='full_name',
            field=models.CharField(blank=True, db_column='ownerFullName', max_length=255),
        ),
        migrations.AlterField(
            model_name='instagrammention',
            name='id',
            field=models.BigAutoField(db_column='django_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instagrammention',
            name='mentioned_user_id',
            field=models.CharField(blank=True, db_column='ownerId', max_length=50),
        ),
        migrations.AlterField(
            model_name='instagrammention',
            name='post_id',
            field=models.CharField(db_column='id', max_length=50),
        ),
        migrations.AlterField(
            model_name='instagrammention',
            name='profile_pic_url',
            field=models.URLField(blank=True, db_column='ownerProfilePicUrl'),
        ),
        migrations.AlterField(
            model_name='instagrammention',
            name='username',
            field=models.CharField(db_column='ownerUsername', max_length=255),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='child_posts',
            field=models.JSONField(db_column='childPosts', default=list),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='comments_count',
            field=models.IntegerField(db_column='commentsCount', default=0),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='dimensions_height',
            field=models.IntegerField(db_column='dimensionsHeight'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='dimensions_width',
            field=models.IntegerField(db_column='dimensionsWidth'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='display_url',
            field=models.URLField(db_column='displayUrl'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='first_comment',
            field=models.TextField(blank=True, db_column='firstComment'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='id',
            field=models.BigAutoField(db_column='django_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='ig_play_count',
            field=models.IntegerField(blank=True, db_column='igPlayCount', null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='input_url',
            field=models.URLField(db_column='inputUrl'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='instagram_id',
            field=models.CharField(db_column='id', max_length=50),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='is_sponsored',
            field=models.BooleanField(db_column='isSponsored', default=False),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='likes_count',
            field=models.IntegerField(db_column='likesCount', default=0),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='music_info',
            field=models.JSONField(blank=True, db_column='musicInfo', null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='owner_full_name',
            field=models.CharField(blank=True, db_column='ownerFullName', max_length=255),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='owner_id',
            field=models.CharField(db_column='ownerId', max_length=50),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='owner_username',
            field=models.CharField(db_column='ownerUsername', max_length=255),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='product_type',
            field=models.CharField(db_column='productType', max_length=50),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='short_code',
            field=models.CharField(db_column='shortCode', max_length=20),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='tagged_users',
            field=models.JSONField(db_column='taggedUsers', default=list),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='video_duration',
            field=models.FloatField(blank=True, db_column='videoDuration', null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='video_play_count',
            field=models.IntegerField(blank=True, db_column='videoPlayCount', null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='video_url',
            field=models.URLField(blank=True, db_column='videoUrl', null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='author_meta',
            field=models.JSONField(blank=True, db_column='authorMeta', help_text='Complete authorMeta object', null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='collect_count',
            field=models.BigIntegerField(db_column='collectCount', default=0),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='comment_count',
            field=models.BigIntegerField(db_column='commentCount', default=0),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='create_time',
            field=models.BigIntegerField(db_column='createTime', help_text='Unix timestamp'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='create_time_iso',
            field=models.DateTimeField(db_column='createTimeISO', help_text='ISO datetime'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='detailed_mentions',
            field=models.JSONField(blank=True, db_column='detailedMentions', default=list),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='digg_count',
            field=models.BigIntegerField(db_column='diggCount', default=0),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='effect_stickers',
            field=models.JSONField(blank=True, db_column='effectStickers', default=list),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='is_ad',
            field=models.BooleanField(db_column='isAd', default=False),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='is_pinned',
            field=models.BooleanField(db_column='isPinned', default=False),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='is_slideshow',
            field=models.BooleanField(db_column='isSlideshow', default=False),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='is_sponsored',
            field=models.BooleanField(db_column='isSponsored', default=False),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='location_created',
            field=models.CharField(blank=True, db_column='locationCreated', max_length=100),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='music_meta',
            field=models.JSONField(blank=True, db_column='musicMeta', help_text='Complete musicMeta object', null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='play_count',
            field=models.BigIntegerField(db_column='playCount', default=0),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='share_count',
            field=models.BigIntegerField(db_column='shareCount', default=0),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='text_language',
            field=models.CharField(blank=True, db_column='textLanguage', help_text="Language code (e.g., 'en')", max_length=10),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='tiktok_id',
            field=models.CharField(db_column='id', help_text='TikTok video ID', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='video_meta',
            field=models.JSONField(blank=True, db_column='videoMeta', help_text='Complete videoMeta object', null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='web_video_url',
            field=models.URLField(blank=True, db_column='webVideoUrl'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='channel_id',
            field=models.CharField(blank=True, db_column='channelId', max_length=50),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='channel_name',
            field=models.CharField(blank=True, db_column='channelName', max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='channel_url',
            field=models.URLField(blank=True, db_column='channelUrl'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='channel_username',
            field=models.CharField(blank=True, db_column='channelUsername', max_length=100),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='comment_count',
            field=models.BigIntegerField(db_column='commentsCount', default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='comments_disabled',
            field=models.BooleanField(db_column='commentsTurnedOff', default=False),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(db_column='duration'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='id',
            field=models.BigAutoField(db_column='django_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='is_members_only',
            field=models.BooleanField(db_column='isMembersOnly', default=False),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='is_monetized',
            field=models.BooleanField(db_column='isMonetized', default=False),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='like_count',
            field=models.BigIntegerField(db_column='likes', default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='published_at',
            field=models.DateTimeField(db_column='date'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='subscriber_count',
            field=models.BigIntegerField(db_column='numberOfSubscribers', default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='text_content',
            field=models.TextField(blank=True, db_column='text'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, db_column='thumbnailUrl'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='translated_title',
            field=models.CharField(blank=True, db_column='translatedTitle', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(db_column='id', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='view_count',
            field=models.BigIntegerField(db_column='viewCount', default=0),
        ),
    ]
