# Generated by Django 5.2.7 on 2025-11-20 15:35

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_column_names_to_camelcase"),
    ]

    operations = [
        # Convert hashtags and mentions from JSONB to text[] arrays using RunSQL with USING clause
        migrations.RunSQL(
            "ALTER TABLE core_instagrampost ALTER COLUMN hashtags TYPE text[] USING CASE WHEN hashtags IS NULL THEN ARRAY[]::text[] ELSE array(SELECT jsonb_array_elements_text(hashtags)) END",
            reverse_sql="ALTER TABLE core_instagrampost ALTER COLUMN hashtags TYPE jsonb USING CASE WHEN hashtags IS NULL THEN '[]'::jsonb ELSE to_jsonb(hashtags) END"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_instagrampost ALTER COLUMN mentions TYPE text[] USING CASE WHEN mentions IS NULL THEN ARRAY[]::text[] ELSE array(SELECT jsonb_array_elements_text(mentions)) END",
            reverse_sql="ALTER TABLE core_instagrampost ALTER COLUMN mentions TYPE jsonb USING CASE WHEN mentions IS NULL THEN '[]'::jsonb ELSE to_jsonb(mentions) END"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_tiktokvideo ALTER COLUMN mentions TYPE text[] USING CASE WHEN mentions IS NULL THEN ARRAY[]::text[] ELSE array(SELECT jsonb_array_elements_text(mentions)) END",
            reverse_sql="ALTER TABLE core_tiktokvideo ALTER COLUMN mentions TYPE jsonb USING CASE WHEN mentions IS NULL THEN '[]'::jsonb ELSE to_jsonb(mentions) END"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_youtubevideo ALTER COLUMN hashtags TYPE text[] USING CASE WHEN hashtags IS NULL THEN ARRAY[]::text[] ELSE array(SELECT jsonb_array_elements_text(hashtags)) END",
            reverse_sql="ALTER TABLE core_youtubevideo ALTER COLUMN hashtags TYPE jsonb USING CASE WHEN hashtags IS NULL THEN '[]'::jsonb ELSE to_jsonb(hashtags) END"
        ),
        # Alter SourceMapping columns to TEXT (has seed data)
        migrations.AlterField(
            model_name="sourcemapping",
            name="source_type",
            field=models.TextField(unique=True, help_text="e.g., youtube-video, instagram-post"),
        ),
        migrations.AlterField(
            model_name="sourcemapping",
            name="target_table",
            field=models.TextField(help_text="e.g., core_youtubevideo, core_instagrampost"),
        ),
        migrations.AlterField(
            model_name="sourcemapping",
            name="platform",
            field=models.TextField(choices=[
                ('youtube', 'YouTube'),
                ('tiktok', 'TikTok'),
                ('instagram', 'Instagram'),
            ], help_text="Social media platform"),
        ),
        # Alter other fields to TEXT type
        migrations.AlterField(
            model_name='instagrampost',
            name='instagram_id',
            field=models.TextField(db_column='id'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='short_code',
            field=models.TextField(db_column='shortCode'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='first_comment',
            field=models.TextField(blank=True, db_column='firstComment'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='owner_full_name',
            field=models.TextField(blank=True, db_column='ownerFullName'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='owner_username',
            field=models.TextField(db_column='ownerUsername'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='owner_id',
            field=models.TextField(db_column='ownerId'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='product_type',
            field=models.TextField(db_column='productType'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='alt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='instagram_id',
            field=models.TextField(db_column='id'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='owner_username',
            field=models.TextField(db_column='ownerUsername'),
        ),
        migrations.AlterField(
            model_name='instagrammention',
            name='post_id',
            field=models.TextField(db_column='id'),
        ),
        migrations.AlterField(
            model_name='instagrammention',
            name='username',
            field=models.TextField(db_column='ownerUsername'),
        ),
        migrations.AlterField(
            model_name='instagrammention',
            name='mentioned_user_id',
            field=models.TextField(blank=True, db_column='ownerId'),
        ),
        migrations.AlterField(
            model_name='instagrammention',
            name='full_name',
            field=models.TextField(blank=True, db_column='ownerFullName'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='tiktok_id',
            field=models.TextField(primary_key=True, db_column='id', help_text="TikTok video ID"),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='text',
            field=models.TextField(blank=True, help_text="Video caption/description"),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='text_language',
            field=models.TextField(blank=True, db_column='textLanguage', help_text="Language code (e.g., 'en')"),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='location_created',
            field=models.TextField(blank=True, db_column='locationCreated'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='author_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='author_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='author_nickname',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='author_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='music_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='music_author',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='music_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='video_definition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='video_format',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.TextField(unique=True, db_column='id'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='translated_title',
            field=models.TextField(blank=True, null=True, db_column='translatedTitle'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='channel_id',
            field=models.TextField(blank=True, db_column='channelId'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='channel_name',
            field=models.TextField(blank=True, db_column='channelName'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='channel_username',
            field=models.TextField(blank=True, db_column='channelUsername'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='text_content',
            field=models.TextField(blank=True, db_column='text'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='language',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='source_type',
            field=models.TextField(),
        ),
    ]
