# Generated by Django 5.2.7 on 2025-11-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_fix_hashtags_fields"),
    ]

    operations = [
        # Alter varchar columns to text in social media tables (only existing varchar columns)
        migrations.RunSQL('ALTER TABLE core_instagrampost ALTER COLUMN id TYPE text'),
        migrations.RunSQL('ALTER TABLE core_instagrampost ALTER COLUMN type TYPE text'),
        migrations.RunSQL('ALTER TABLE core_instagrampost ALTER COLUMN "shortCode" TYPE text'),
        migrations.RunSQL('ALTER TABLE core_instagrampost ALTER COLUMN "ownerFullName" TYPE text'),
        migrations.RunSQL('ALTER TABLE core_instagrampost ALTER COLUMN "ownerUsername" TYPE text'),
        migrations.RunSQL('ALTER TABLE core_instagrampost ALTER COLUMN "ownerId" TYPE text'),
        migrations.RunSQL('ALTER TABLE core_instagrampost ALTER COLUMN "productType" TYPE text'),

        migrations.RunSQL('ALTER TABLE core_instagramcomment ALTER COLUMN id TYPE text'),
        migrations.RunSQL('ALTER TABLE core_instagramcomment ALTER COLUMN "ownerUsername" TYPE text'),

        migrations.RunSQL('ALTER TABLE core_instagrammention ALTER COLUMN id TYPE text'),
        migrations.RunSQL('ALTER TABLE core_instagrammention ALTER COLUMN "ownerUsername" TYPE text'),
        migrations.RunSQL('ALTER TABLE core_instagrammention ALTER COLUMN "ownerId" TYPE text'),
        migrations.RunSQL('ALTER TABLE core_instagrammention ALTER COLUMN "ownerFullName" TYPE text'),

        # TikTokVideo columns
        migrations.RunSQL('ALTER TABLE core_tiktokvideo ALTER COLUMN id TYPE text'),
        migrations.RunSQL('ALTER TABLE core_tiktokvideo ALTER COLUMN "textLanguage" TYPE text'),
        migrations.RunSQL('ALTER TABLE core_tiktokvideo ALTER COLUMN "locationCreated" TYPE text'),
        migrations.RunSQL('ALTER TABLE core_tiktokvideo ALTER COLUMN author_id TYPE text'),
        migrations.RunSQL('ALTER TABLE core_tiktokvideo ALTER COLUMN author_name TYPE text'),
        migrations.RunSQL('ALTER TABLE core_tiktokvideo ALTER COLUMN author_nickname TYPE text'),
        migrations.RunSQL('ALTER TABLE core_tiktokvideo ALTER COLUMN music_name TYPE text'),
        migrations.RunSQL('ALTER TABLE core_tiktokvideo ALTER COLUMN music_author TYPE text'),
        migrations.RunSQL('ALTER TABLE core_tiktokvideo ALTER COLUMN music_id TYPE text'),
        migrations.RunSQL('ALTER TABLE core_tiktokvideo ALTER COLUMN video_format TYPE text'),

        migrations.RunSQL('ALTER TABLE core_youtubevideo ALTER COLUMN id TYPE text'),
        migrations.RunSQL('ALTER TABLE core_youtubevideo ALTER COLUMN title TYPE text'),
        migrations.RunSQL('ALTER TABLE core_youtubevideo ALTER COLUMN "translatedTitle" TYPE text'),
        migrations.RunSQL('ALTER TABLE core_youtubevideo ALTER COLUMN "channelId" TYPE text'),
        migrations.RunSQL('ALTER TABLE core_youtubevideo ALTER COLUMN "channelName" TYPE text'),
        migrations.RunSQL('ALTER TABLE core_youtubevideo ALTER COLUMN "channelUsername" TYPE text'),
        migrations.RunSQL('ALTER TABLE core_youtubevideo ALTER COLUMN language TYPE text'),
        migrations.RunSQL('ALTER TABLE core_youtubevideo ALTER COLUMN category TYPE text'),
        migrations.RunSQL('ALTER TABLE core_youtubevideo ALTER COLUMN source_type TYPE text'),

        migrations.RunSQL('ALTER TABLE core_sourcemapping ALTER COLUMN source_type TYPE text'),
        migrations.RunSQL('ALTER TABLE core_sourcemapping ALTER COLUMN target_table TYPE text'),
        migrations.RunSQL('ALTER TABLE core_sourcemapping ALTER COLUMN platform TYPE text'),
    ]
