# Generated by Django 5.2.7 on 2025-11-20 18:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_varchar_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcomment',
            name='comment_url',
            field=models.TextField(db_column='commentUrl'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='owner_profile_pic_url',
            field=models.TextField(db_column='ownerProfilePicUrl'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='post_url',
            field=models.TextField(db_column='postUrl'),
        ),
        migrations.AlterField(
            model_name='instagrammention',
            name='profile_pic_url',
            field=models.TextField(blank=True, db_column='ownerProfilePicUrl'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='audio_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='display_url',
            field=models.TextField(db_column='displayUrl'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='input_url',
            field=models.TextField(db_column='inputUrl'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='mentions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='video_url',
            field=models.TextField(blank=True, db_column='videoUrl', null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='author_avatar_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='author_bio_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='author_profile_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='mentions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='music_cover_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='music_play_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='tiktok_id',
            field=models.TextField(db_column='id', help_text='TikTok video ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='video_cover_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='web_video_url',
            field=models.TextField(blank=True, db_column='webVideoUrl'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='channel_url',
            field=models.TextField(blank=True, db_column='channelUrl'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='thumbnail_url',
            field=models.TextField(blank=True, db_column='thumbnailUrl'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
