#!/usr/bin/env python
"""
YouTube Source Testing Script

This script runs individual YouTube source tests to validate Apify parameter parsing.
Each test is run separately to allow workflow restarts between tests.

Usage:
    python test_youtube_sources.py [--source-type TYPE] [--list-types]

Options:
    --source-type TYPE    Run specific test (youtube-search, youtube-channel, etc.)
    --list-types         List all available test types
"""

import os
import sys
import json
import django
from django.conf import settings

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'vibe_scraper.settings')
django.setup()

from django.test import TestCase
from unittest.mock import patch, MagicMock
from core.models import Run
from core.views import build_source_config, trigger_run
from django.contrib.auth import get_user_model

User = get_user_model()

# Test configurations with max_results=1 for cost control
YOUTUBE_TEST_CONFIGS = {
    'youtube-search': {
        'sourceType': 'youtube-search',
        'config': {
            'searchQueries': ['python tutorial'],
            'maxResults': 1,
            'maxResultsShorts': 0,
            'maxResultStreams': 0,
            'sortingOrder': 'relevance',
            'dateFilter': '',
            'videoType': 'video',
            'lengthFilter': '',
            'qualityFilters': {
                'isHD': False,
                'hasSubtitles': False,
                'hasCC': False,
                'is3D': False,
                'isLive': False,
                'is4K': False,
                'is360': False,
                'hasLocation': False,
                'isHDR': False,
                'isVR180': False,
                'isBought': False,
            },
            'subtitleOptions': {
                'language': 'any',
                'downloadSubtitles': False,
                'saveSubsToKVS': False,
                'preferAutoGeneratedSubtitles': False,
                'subtitlesFormat': 'srt',
            }
        }
    },
    
    'youtube-channel': {
        'sourceType': 'youtube-channel',
        'config': {
            'startUrls': ['https://youtube.com/channel/UCtest123'],
            'maxResults': 1,
            'maxResultsShorts': 0,
            'maxResultStreams': 0,
            'sortingOrder': 'date',
            'dateFilter': '',
            'videoType': 'video',
            'lengthFilter': '',
            'qualityFilters': {
                'isHD': False,
                'hasSubtitles': False,
                'hasCC': False,
                'is3D': False,
                'isLive': False,
                'is4K': False,
                'is360': False,
                'hasLocation': False,
                'isHDR': False,
                'isVR180': False,
                'isBought': False,
            },
            'subtitleOptions': {
                'language': 'any',
                'downloadSubtitles': False,
                'saveSubsToKVS': False,
                'preferAutoGeneratedSubtitles': False,
                'subtitlesFormat': 'srt',
            }
        }
    },
    
    'youtube-playlist': {
        'sourceType': 'youtube-playlist',
        'config': {
            'startUrls': ['https://youtube.com/playlist?list=PLtest123'],
            'maxResults': 1,
            'maxResultsShorts': 0,
            'maxResultStreams': 0,
            'sortingOrder': 'date',
            'dateFilter': '',
            'videoType': 'video',
            'lengthFilter': '',
            'qualityFilters': {
                'isHD': False,
                'hasSubtitles': False,
                'hasCC': False,
                'is3D': False,
                'isLive': False,
                'is4K': False,
                'is360': False,
                'hasLocation': False,
                'isHDR': False,
                'isVR180': False,
                'isBought': False,
            },
            'subtitleOptions': {
                'language': 'any',
                'downloadSubtitles': False,
                'saveSubsToKVS': False,
                'preferAutoGeneratedSubtitles': False,
                'subtitlesFormat': 'srt',
            }
        }
    },
    
    'youtube-hashtag': {
        'sourceType': 'youtube-hashtag',
        'config': {
            'startUrls': ['https://youtube.com/hashtag/python'],
            'maxResults': 1,
            'maxResultsShorts': 0,
            'maxResultStreams': 0,
            'sortingOrder': 'date',
            'dateFilter': '',
            'videoType': 'video',
            'lengthFilter': '',
            'qualityFilters': {
                'isHD': False,
                'hasSubtitles': False,
                'hasCC': False,
                'is3D': False,
                'isLive': False,
                'is4K': False,
                'is360': False,
                'hasLocation': False,
                'isHDR': False,
                'isVR180': False,
                'isBought': False,
            },
            'subtitleOptions': {
                'language': 'any',
                'downloadSubtitles': False,
                'saveSubsToKVS': False,
                'preferAutoGeneratedSubtitles': False,
                'subtitlesFormat': 'srt',
            }
        }
    },
    
    'youtube-video': {
        'sourceType': 'youtube-video',
        'config': {
            'startUrls': ['https://youtube.com/watch?v=dQw4w9WgXcQ'],
            'maxResults': 1,
            'maxResultsShorts': 0,
            'maxResultStreams': 0,
            'sortingOrder': 'date',
            'dateFilter': '',
            'videoType': 'video',
            'lengthFilter': '',
            'qualityFilters': {
                'isHD': False,
                'hasSubtitles': False,
                'hasCC': False,
                'is3D': False,
                'isLive': False,
                'is4K': False,
                'is360': False,
                'hasLocation': False,
                'isHDR': False,
                'isVR180': False,
                'isBought': False,
            },
            'subtitleOptions': {
                'language': 'any',
                'downloadSubtitles': False,
                'saveSubsToKVS': False,
                'preferAutoGeneratedSubtitles': False,
                'subtitlesFormat': 'srt',
            }
        }
    }
}

def create_test_user():
    """Create test user"""
    user, created = User.objects.get_or_create(
        username='testuser',
        defaults={
            'email': 'test@example.com',
        }
    )
    if created:
        user.set_password('testpass123')
        user.save()
    return user

def test_config_generation(source_type):
    """Test configuration generation for specific source type"""
    print(f"\n🧪 Testing {source_type} configuration generation...")
    
    # Create test form data
    if source_type == 'youtube-search':
        cleaned_data = {
            'source_type': source_type,
            'search_queries': 'python tutorial\ndjango development',
            'max_results': 1,
            'sorting_order': 'relevance',
            'date_filter': '',
            'video_type': 'video',
            'length_filter': '',
            'is_hd': False,
            'has_subtitles': False,
            'has_cc': False,
            'is_3d': False,
            'is_live': False,
            'is_4k': False,
            'is_360': False,
            'has_location': False,
            'is_hdr': False,
            'is_vr180': False,
            'is_bought': False,
            'subtitles_language': 'any',
            'download_subtitles': False,
            'save_subs_to_kvs': False,
            'prefer_auto_generated_subtitles': False,
            'subtitles_format': 'srt',
        }
    else:
        cleaned_data = {
            'source_type': source_type,
            'profile_urls': YOUTUBE_TEST_CONFIGS[source_type]['config']['startUrls'][0],
            'max_results': 1,
            'sorting_order': 'date',
            'date_filter': '',
            'video_type': 'video',
            'length_filter': '',
            'is_hd': False,
            'has_subtitles': False,
            'has_cc': False,
            'is_3d': False,
            'is_live': False,
            'is_4k': False,
            'is_360': False,
            'has_location': False,
            'is_hdr': False,
            'is_vr180': False,
            'is_bought': False,
            'subtitles_language': 'any',
            'download_subtitles': False,
            'save_subs_to_kvs': False,
            'prefer_auto_generated_subtitles': False,
            'subtitles_format': 'srt',
        }
    
    # Generate configuration
    cleaned_data_with_source_type = cleaned_data.copy()
    cleaned_data_with_source_type['source_type'] = source_type
    config = build_source_config(cleaned_data_with_source_type)
    
    # Validate configuration
    expected_config = YOUTUBE_TEST_CONFIGS[source_type]['config']
    
    print(f"✅ Generated configuration for {source_type}:")
    print(json.dumps(config, indent=2))
    
    # Basic validation
    assert config['maxResults'] == 1, f"maxResults should be 1, got {config['maxResults']}"
    assert config['maxResultsShorts'] == 0, f"maxResultsShorts should be 0, got {config['maxResultsShorts']}"
    assert config['maxResultStreams'] == 0, f"maxResultStreams should be 0, got {config['maxResultStreams']}"
    
    if source_type == 'youtube-search':
        assert 'searchQueries' in config, f"searchQueries missing from {source_type} config"
        assert 'startUrls' not in config, f"startUrls should not be in {source_type} config"
    else:
        assert 'startUrls' in config, f"startUrls missing from {source_type} config"
        assert 'searchQueries' not in config, f"searchQueries should not be in {source_type} config"
    
    print(f"✅ {source_type} configuration validation passed!")

def test_webhook_trigger(source_type):
    """Test webhook triggering for specific source type"""
    print(f"\n🚀 Testing {source_type} webhook trigger...")
    
    # Create test user
    user = create_test_user()
    
    # Create run with test configuration
    run = Run.objects.create(
        user=user,
        input=json.dumps({
            'sources': [YOUTUBE_TEST_CONFIGS[source_type]],
            'max_results': 1,
            'days_since': 14,
            'auto_infer_columns': True,
            'custom_columns': [],
            'extraction_prompt': "Extract location information, business mentions, contact details, and other relevant data from social media posts. Adapt to the specific platform and content type.",
            'enable_extraction': True
        })
    )
    
    print(f"✅ Created test run {run.pk} for {source_type}")
    
    # Print the exact payload that will be sent to n8n
    input_data = json.loads(run.input)
    payload = {
        "sources": [],
        "daysSince": input_data.get('days_since', 14),
        "maxResults": input_data.get('max_results', 1),
        "auto_infer_columns": input_data.get('auto_infer_columns', True),
        "custom_columns": input_data.get('custom_columns', []),
        "enable_extraction": input_data.get('enable_extraction', True),
        "extraction_prompt": input_data.get('extraction_prompt', "")
    }
    
    # Convert sources to platform format
    for source in input_data.get('sources', []):
        source_type = source.get('sourceType', '')
        config = source.get('config', {})
        
        # Map sourceType to platform
        if source_type.startswith('youtube-'):
            platform = 'youtube'
        elif source_type.startswith('instagram-'):
            platform = 'instagram'
        elif source_type.startswith('tiktok-'):
            platform = 'tiktok'
        else:
            platform = 'instagram'
        
        platform_source = {
            'platform': platform,
            'sourceType': source_type,
            'configuration': config
        }
        
        payload['sources'].append(platform_source)
    
    print(f"📤 Payload that will be sent to n8n:")
    print(json.dumps(payload, indent=2))
    
    # Get webhook URL
    webhook_url = getattr(settings, 'N8N_TEST_SCRAPING_URL', 'http://localhost:5678/webhook-test/multi-source-scrape')
    print(f"🌐 Webhook URL: {webhook_url}")
    
    print(f"✅ {source_type} webhook test prepared!")
    print(f"📋 Ready to trigger n8n workflow")
    print(f"💡 You can now start the n8n workflow and monitor the execution")
    
    return run, payload

def list_test_types():
    """List all available test types"""
    print("\n📋 Available YouTube source test types:")
    for i, source_type in enumerate(YOUTUBE_TEST_CONFIGS.keys(), 1):
        print(f"  {i}. {source_type}")

def main():
    """Main function"""
    if '--list-types' in sys.argv:
        list_test_types()
        return
    
    if '--source-type' not in sys.argv:
        print("❌ Error: --source-type is required")
        print("Use --list-types to see available options")
        sys.exit(1)
    
    source_type = sys.argv[sys.argv.index('--source-type') + 1]
    
    if source_type not in YOUTUBE_TEST_CONFIGS:
        print(f"❌ Error: Unknown source type '{source_type}'")
        print("Use --list-types to see available options")
        sys.exit(1)
    
    print(f"🎬 Starting YouTube source test for: {source_type}")
    print("=" * 60)
    
    try:
        # Test configuration generation
        test_config_generation(source_type)
        
        # Test webhook trigger
        run, payload = test_webhook_trigger(source_type)
        
        print("\n" + "=" * 60)
        print(f"✅ All tests prepared for {source_type}")
        print(f"🚀 Ready to execute!")
        print(f"\n📝 Next steps:")
        print(f"   1. Start n8n workflow (if not already running)")
        print(f"   2. Monitor execution at: http://localhost:5678")
        print(f"   3. Check Apify parameters in execution logs")
        print(f"   4. Verify cost control (maxResults=1)")
        
    except Exception as e:
        print(f"❌ Error during testing: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == '__main__':
    main()