from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField


class User(AbstractUser):
    # Extend for Supabase integration later
    supabase_id = models.CharField(max_length=255, blank=True, null=True)
    subscription_tier = models.CharField(max_length=50, default='free')
    api_credits = models.IntegerField(default=0) 

class Run(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    n8n_execution_id = models.BigIntegerField(blank=True, null=True, db_index=True)
    input = models.JSONField(null=True)  # Scraping parameters (URLs, extraction specs, etc.)
    extraction_prompt = models.TextField(blank=True, default="Extract location information, business mentions, contact details, and other relevant data from social media posts. Adapt to the specific platform and content type.", help_text="Custom prompt for AI extraction")
    enable_extraction = models.BooleanField(default=True, help_text="Whether to run LLM extraction on scraped data")
    enhanced_prompt = models.TextField(blank=True, null=True, help_text="Enhanced extraction prompt generated by n8n workflow")
    scraped = models.JSONField(null=True, help_text="Raw scraped data organized by platform: {'instagram': [...], 'tiktok': [...], ...}")
    extracted = models.JSONField(null=True, help_text="Processed entities extracted from scraped data")
    # Keep output temporarily for backward compatibility
    output = models.JSONField(null=True)  # DEPRECATED: Will be removed after migration
    created_at = models.DateTimeField(auto_now_add=True)



class UserList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    icon = models.CharField(max_length=50, blank=True, help_text="Emoji or icon for the list")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "User List"
        verbose_name_plural = "User Lists"


class ListColumn(models.Model):
    COLUMN_TYPES = [
        ('text', 'Text'),
        ('number', 'Number'),
        ('date', 'Date'),
        ('boolean', 'Boolean'),
        ('select', 'Select'),
        ('multi_select', 'Multi Select'),
        ('url', 'URL'),
        ('json', 'JSON'),
    ]

    user_list = models.ForeignKey(UserList, on_delete=models.CASCADE, related_name='columns')
    name = models.CharField(max_length=255)
    column_type = models.CharField(max_length=20, choices=COLUMN_TYPES, default='text')
    description = models.TextField(blank=True, help_text="Optional description of what this column contains")
    required = models.BooleanField(default=False)
    order = models.PositiveIntegerField(default=0)
    options = models.JSONField(null=True, blank=True)  # For select/multi_select options
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['order', 'created_at']
        unique_together = ['user_list', 'name']

    def __str__(self):
        return f"{self.user_list.name} - {self.name} ({self.column_type})"
    
    @property
    def field(self):
        """Generate field name for AG-Grid (slugified column name)"""
        return self.name.lower().replace(' ', '_').replace('-', '_')


class ListRow(models.Model):
    user_list = models.ForeignKey(UserList, on_delete=models.CASCADE, related_name='rows')
    data = models.JSONField()  # Stores the row data as JSON
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']


class SourceMapping(models.Model):
    source_type = models.TextField(unique=True, help_text="e.g., youtube-video, instagram-post")
    target_table = models.TextField(help_text="e.g., core_youtubevideo, core_instagrampost")
    platform = models.TextField(choices=[
        ('youtube', 'YouTube'),
        ('tiktok', 'TikTok'),
        ('instagram', 'Instagram'),
    ], help_text="Social media platform")
    description = models.TextField(blank=True, help_text="Optional description of what this source does")

    class Meta:
        app_label = 'core'
        ordering = ['platform', 'source_type']

    def __str__(self):
        return f"{self.source_type} -> {self.target_table}"
    



class InstagramPost(models.Model):
    id = models.TextField(primary_key=True, db_column='id')

    inputUrl = models.TextField(db_column='inputUrl')
    type = models.TextField(db_column='type')
    shortCode = models.TextField(db_column='shortCode')
    caption = models.TextField(blank=True, db_column='caption')
    hashtags = ArrayField(models.TextField(), default=list, blank=True, db_column='hashtags')
    mentions = ArrayField(models.TextField(), default=list, blank=True, db_column='mentions')
    url = models.TextField(db_column='url')
    commentsCount = models.PositiveBigIntegerField(default=0, db_column='commentsCount')
    firstComment = models.TextField(blank=True, db_column='firstComment')
    latestComments = models.JSONField(default=list, blank=True, db_column='latestComments')

    dimensionsHeight = models.PositiveIntegerField(db_column='dimensionsHeight')
    dimensionsWidth = models.PositiveIntegerField(db_column='dimensionsWidth')
    displayUrl = models.TextField(db_column='displayUrl')
    images = models.JSONField(default=list, blank=True, db_column='images')
    videoUrl = models.TextField(blank=True, null=True, db_column='videoUrl')
    audioUrl = models.TextField(blank=True, null=True, db_column='audioUrl')

    likesCount = models.PositiveBigIntegerField(default=0, db_column='likesCount')
    videoPlayCount = models.PositiveBigIntegerField(null=True, blank=True, db_column='videoPlayCount')
    igPlayCount = models.PositiveBigIntegerField(null=True, blank=True, db_column='igPlayCount')
    videoViewCount = models.PositiveBigIntegerField(null=True, blank=True, db_column='videoViewCount')
    videoDuration = models.FloatField(null=True, blank=True, db_column='videoDuration')

    timestamp = models.DateTimeField(db_column='timestamp')

    ownerFullName = models.TextField(blank=True, db_column='ownerFullName')
    ownerUsername = models.TextField(db_column='ownerUsername')
    ownerId = models.TextField(db_column='ownerId')

    productType = models.TextField(blank=True, db_column='productType')
    isSponsored = models.BooleanField(default=False, db_column='isSponsored')

    taggedUsers = models.JSONField(default=list, blank=True, db_column='taggedUsers')
    childPosts = models.JSONField(default=list, blank=True, db_column='childPosts')
    musicInfo = models.JSONField(null=True, blank=True, db_column='musicInfo')

    # ONLY TWO FOREIGN KEYS
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='instagram_posts')
    run = models.ForeignKey('Run', on_delete=models.CASCADE, related_name='instagram_posts')

    extracted_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'data_instagram_posts'
        indexes = [
            models.Index(fields=['run']),
            models.Index(fields=['user']),
            models.Index(fields=['run', '-timestamp']),
        ]


class InstagramComment(models.Model):
    id = models.TextField(primary_key=True, db_column='id')

    postUrl = models.TextField(db_column='postUrl')
    commentUrl = models.TextField(blank=True, db_column='commentUrl')
    text = models.TextField(db_column='text')
    ownerUsername = models.TextField(db_column='ownerUsername')
    ownerProfilePicUrl = models.TextField(blank=True, db_column='ownerProfilePicUrl')
    timestamp = models.DateTimeField(db_column='timestamp')
    repliesCount = models.PositiveIntegerField(default=0, db_column='repliesCount')
    replies = models.JSONField(default=list, blank=True, db_column='replies')
    likesCount = models.PositiveIntegerField(default=0, db_column='likesCount')
    owner = models.JSONField(default=dict, blank=True, db_column='owner')

    # ONLY TWO FOREIGN KEYS
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='instagram_comments')
    run = models.ForeignKey('Run', on_delete=models.CASCADE, related_name='instagram_comments')

    extracted_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'data_instagram_comments'
        indexes = [
            models.Index(fields=['run']),
            models.Index(fields=['user']),
            models.Index(fields=['postUrl']),
            models.Index(fields=['-timestamp']),
        ]

class TikTokVideo(models.Model):
    id = models.TextField(primary_key=True, db_column='id')

    text = models.TextField(blank=True, db_column='text')
    textLanguage = models.TextField(blank=True, db_column='textLanguage')
    createTime = models.BigIntegerField(null=True, blank=True, db_column='createTime')
    createTimeISO = models.DateTimeField(null=True, blank=True, db_column='createTimeISO')
    isAd = models.BooleanField(default=False, db_column='isAd')

    authorMeta = models.JSONField(default=dict, blank=True, db_column='authorMeta')
    musicMeta = models.JSONField(default=dict, blank=True, db_column='musicMeta')

    webVideoUrl = models.TextField(db_column='webVideoUrl')
    mediaUrls = models.JSONField(default=list, blank=True, db_column='mediaUrls')
    videoMeta = models.JSONField(default=dict, blank=True, db_column='videoMeta')

    diggCount = models.PositiveBigIntegerField(default=0, db_column='diggCount')
    shareCount = models.PositiveBigIntegerField(default=0, db_column='shareCount')
    playCount = models.PositiveBigIntegerField(default=0, db_column='playCount')
    collectCount = models.PositiveBigIntegerField(default=0, db_column='collectCount')
    commentCount = models.PositiveBigIntegerField(default=0, db_column='commentCount')

    mentions = models.JSONField(default=list, blank=True, db_column='mentions')
    detailedMentions = models.JSONField(default=list, blank=True, db_column='detailedMentions')
    hashtags = models.JSONField(default=list, blank=True, db_column='hashtags')
    effectStickers = models.JSONField(default=list, blank=True, db_column='effectStickers')

    isSlideshow = models.BooleanField(default=False, db_column='isSlideshow')
    isPinned = models.BooleanField(default=False, db_column='isPinned')
    isSponsored = models.BooleanField(default=False, db_column='isSponsored')

    input = models.TextField(blank=True, db_column='input')
    fromProfileSection = models.TextField(blank=True, db_column='fromProfileSection')
    submittedVideoUrl = models.TextField(blank=True, db_column='submittedVideoUrl')

    # ONLY TWO FOREIGN KEYS
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tiktok_videos')
    run = models.ForeignKey('Run', on_delete=models.CASCADE, related_name='tiktok_videos')

    extracted_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'data_tiktok_videos'
        indexes = [
            models.Index(fields=['run']),
            models.Index(fields=['user']),
            models.Index(fields=['run', '-createTimeISO']),
        ]

    def __str__(self):
        return f"TikTok {self.id}"
    



class YouTubeVideo(models.Model):
    id = models.TextField(primary_key=True, db_column='id')

    title = models.TextField(db_column='title')
    translatedTitle = models.TextField(null=True, blank=True, db_column='translatedTitle')
    type = models.TextField(db_column='type')
    url = models.TextField(db_column='url')
    thumbnailUrl = models.TextField(blank=True, db_column='thumbnailUrl')
    viewCount = models.BigIntegerField(null=True, blank=True, db_column='viewCount')
    date = models.DateTimeField(null=True, blank=True, db_column='date')
    likes = models.BigIntegerField(null=True, blank=True, db_column='likes')
    location = models.TextField(blank=True, db_column='location')
    channelName = models.TextField(db_column='channelName')
    channelUrl = models.TextField(db_column='channelUrl')
    channelUsername = models.TextField(blank=True, db_column='channelUsername')
    channelId = models.TextField(db_column='channelId')
    numberOfSubscribers = models.BigIntegerField(null=True, blank=True, db_column='numberOfSubscribers')
    duration = models.TextField(blank=True, db_column='duration')
    commentsCount = models.BigIntegerField(null=True, blank=True, db_column='commentsCount')
    text = models.TextField(blank=True, db_column='text')
    translatedText = models.TextField(blank=True, db_column='translatedText')
    descriptionLinks = models.JSONField(default=list, blank=True, db_column='descriptionLinks')
    subtitles = models.JSONField(default=list, blank=True, db_column='subtitles')
    hashtags = models.JSONField(default=list, blank=True, db_column='hashtags')
    formats = models.JSONField(default=list, blank=True, db_column='formats')
    commentsTurnedOff = models.BooleanField(default=False, db_column='commentsTurnedOff')
    isMembersOnly = models.BooleanField(default=False, db_column='isMembersOnly')
    isMonetized = models.BooleanField(null=True, blank=True, db_column='isMonetized')
    order = models.IntegerField(null=True, blank=True, db_column='order')
    fromYTUrl = models.TextField(blank=True, db_column='fromYTUrl')
    input = models.TextField(blank=True, db_column='input')
    fromChannelListPage = models.TextField(blank=True, db_column='fromChannelListPage')

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='youtube_videos')
    run = models.ForeignKey('Run', on_delete=models.CASCADE, related_name='youtube_videos')
    extracted_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'data_youtube_videos'
        indexes = [
            models.Index(fields=['run']),
            models.Index(fields=['user']),
        ]



