import json
import logging
from django.test import TestCase, override_settings
from django.contrib.auth import get_user_model
from unittest.mock import patch, MagicMock
import requests
from core.models import Run
from core.views import build_source_config, trigger_run

User = get_user_model()
logger = logging.getLogger(__name__)

class YouTubeSourceTestCase(TestCase):
    """Test YouTube source configurations for multi-source scraping"""
    
    def setUp(self):
        """Set up test environment"""
        self.test_user = User.objects.create_user(
            username='testuser',
            email='test@example.com',
            password='testpass123'
        )
        
        # Test configurations with max_results=1 for cost control
        self.youtube_test_configs = {
            'youtube-search': {
                'sourceType': 'youtube-search',
                'config': {
                    'searchQueries': ['python tutorial'],
                    'maxResults': 1,
                    'maxResultsShorts': 0,
                    'maxResultStreams': 0,
                    'sortingOrder': 'relevance',
                    'dateFilter': '',
                    'videoType': 'video',
                    'lengthFilter': '',
                    'qualityFilters': {
                        'isHD': False,
                        'hasSubtitles': False,
                        'hasCC': False,
                        'is3D': False,
                        'isLive': False,
                        'is4K': False,
                        'is360': False,
                        'hasLocation': False,
                        'isHDR': False,
                        'isVR180': False,
                        'isBought': False,
                    },
                    'subtitleOptions': {
                        'language': 'any',
                        'downloadSubtitles': False,
                        'saveSubsToKVS': False,
                        'preferAutoGeneratedSubtitles': False,
                        'subtitlesFormat': 'srt',
                    }
                }
            },
            
            'youtube-channel': {
                'sourceType': 'youtube-channel',
                'config': {
                    'startUrls': ['https://youtube.com/channel/UCtest123'],
                    'maxResults': 1,
                    'maxResultsShorts': 0,
                    'maxResultStreams': 0,
                    'sortingOrder': 'date',
                    'dateFilter': '',
                    'videoType': 'video',
                    'lengthFilter': '',
                    'qualityFilters': {
                        'isHD': False,
                        'hasSubtitles': False,
                        'hasCC': False,
                        'is3D': False,
                        'isLive': False,
                        'is4K': False,
                        'is360': False,
                        'hasLocation': False,
                        'isHDR': False,
                        'isVR180': False,
                        'isBought': False,
                    },
                    'subtitleOptions': {
                        'language': 'any',
                        'downloadSubtitles': False,
                        'saveSubsToKVS': False,
                        'preferAutoGeneratedSubtitles': False,
                        'subtitlesFormat': 'srt',
                    }
                }
            },
            
            'youtube-playlist': {
                'sourceType': 'youtube-playlist',
                'config': {
                    'startUrls': ['https://youtube.com/playlist?list=PLtest123'],
                    'maxResults': 1,
                    'maxResultsShorts': 0,
                    'maxResultStreams': 0,
                    'sortingOrder': 'date',
                    'dateFilter': '',
                    'videoType': 'video',
                    'lengthFilter': '',
                    'qualityFilters': {
                        'isHD': False,
                        'hasSubtitles': False,
                        'hasCC': False,
                        'is3D': False,
                        'isLive': False,
                        'is4K': False,
                        'is360': False,
                        'hasLocation': False,
                        'isHDR': False,
                        'isVR180': False,
                        'isBought': False,
                    },
                    'subtitleOptions': {
                        'language': 'any',
                        'downloadSubtitles': False,
                        'saveSubsToKVS': False,
                        'preferAutoGeneratedSubtitles': False,
                        'subtitlesFormat': 'srt',
                    }
                }
            },
            
            'youtube-hashtag': {
                'sourceType': 'youtube-hashtag',
                'config': {
                    'startUrls': ['https://youtube.com/hashtag/python'],
                    'maxResults': 1,
                    'maxResultsShorts': 0,
                    'maxResultStreams': 0,
                    'sortingOrder': 'date',
                    'dateFilter': '',
                    'videoType': 'video',
                    'lengthFilter': '',
                    'qualityFilters': {
                        'isHD': False,
                        'hasSubtitles': False,
                        'hasCC': False,
                        'is3D': False,
                        'isLive': False,
                        'is4K': False,
                        'is360': False,
                        'hasLocation': False,
                        'isHDR': False,
                        'isVR180': False,
                        'isBought': False,
                    },
                    'subtitleOptions': {
                        'language': 'any',
                        'downloadSubtitles': False,
                        'saveSubsToKVS': False,
                        'preferAutoGeneratedSubtitles': False,
                        'subtitlesFormat': 'srt',
                    }
                }
            },
            
            'youtube-video': {
                'sourceType': 'youtube-video',
                'config': {
                    'startUrls': ['https://youtube.com/watch?v=dQw4w9WgXcQ'],
                    'maxResults': 1,
                    'maxResultsShorts': 0,
                    'maxResultStreams': 0,
                    'sortingOrder': 'date',
                    'dateFilter': '',
                    'videoType': 'video',
                    'lengthFilter': '',
                    'qualityFilters': {
                        'isHD': False,
                        'hasSubtitles': False,
                        'hasCC': False,
                        'is3D': False,
                        'isLive': False,
                        'is4K': False,
                        'is360': False,
                        'hasLocation': False,
                        'isHDR': False,
                        'isVR180': False,
                        'isBought': False,
                    },
                    'subtitleOptions': {
                        'language': 'any',
                        'downloadSubtitles': False,
                        'saveSubsToKVS': False,
                        'preferAutoGeneratedSubtitles': False,
                        'subtitlesFormat': 'srt',
                    }
                }
            }
        }

    def test_youtube_search_config_generation(self):
        """Test YouTube search configuration generation"""
        cleaned_data = {
            'source_type': 'youtube-search',
            'search_queries': 'python tutorial\ndjango development',
            'max_results': 1,
            'sorting_order': 'relevance',
            'date_filter': '',
            'video_type': 'video',
            'length_filter': '',
            'is_hd': False,
            'has_subtitles': False,
            'has_cc': False,
            'is_3d': False,
            'is_live': False,
            'is_4k': False,
            'is_360': False,
            'has_location': False,
            'is_hdr': False,
            'is_vr180': False,
            'is_bought': False,
            'subtitles_language': 'any',
            'download_subtitles': False,
            'save_subs_to_kvs': False,
            'prefer_auto_generated_subtitles': False,
            'subtitles_format': 'srt',
        }
        
        config = build_source_config('youtube-search', cleaned_data)
        
        # Validate search-specific configuration
        self.assertEqual(config['searchQueries'], ['python tutorial', 'django development'])
        self.assertEqual(config['maxResults'], 1)
        self.assertEqual(config['maxResultsShorts'], 0)
        self.assertEqual(config['maxResultStreams'], 0)
        self.assertEqual(config['sortingOrder'], 'relevance')
        self.assertEqual(config['dateFilter'], '')
        self.assertEqual(config['videoType'], 'video')
        self.assertEqual(config['lengthFilter'], '')
        
        # Validate quality filters
        self.assertFalse(config['qualityFilters']['isHD'])
        self.assertFalse(config['qualityFilters']['hasSubtitles'])
        self.assertFalse(config['qualityFilters']['hasCC'])
        self.assertFalse(config['qualityFilters']['is3D'])
        self.assertFalse(config['qualityFilters']['isLive'])
        self.assertFalse(config['qualityFilters']['is4K'])
        self.assertFalse(config['qualityFilters']['is360'])
        self.assertFalse(config['qualityFilters']['hasLocation'])
        self.assertFalse(config['qualityFilters']['isHDR'])
        self.assertFalse(config['qualityFilters']['isVR180'])
        self.assertFalse(config['qualityFilters']['isBought'])
        
        # Validate subtitle options
        self.assertEqual(config['subtitleOptions']['language'], 'any')
        self.assertFalse(config['subtitleOptions']['downloadSubtitles'])
        self.assertFalse(config['subtitleOptions']['saveSubsToKVS'])
        self.assertFalse(config['subtitleOptions']['preferAutoGeneratedSubtitles'])
        self.assertEqual(config['subtitleOptions']['subtitlesFormat'], 'srt')
        
        # Ensure startUrls is not set for search
        self.assertNotIn('startUrls', config)

    def test_youtube_channel_config_generation(self):
        """Test YouTube channel configuration generation"""
        cleaned_data = {
            'source_type': 'youtube-channel',
            'profile_urls': 'https://youtube.com/channel/UCtest123\nhttps://youtube.com/channel/UCtest456',
            'max_results': 1,
            'sorting_order': 'date',
            'date_filter': 'month',
            'video_type': 'video',
            'length_filter': '',
            'is_hd': True,
            'has_subtitles': True,
            'has_cc': False,
            'is_3d': False,
            'is_live': False,
            'is_4k': False,
            'is_360': False,
            'has_location': False,
            'is_hdr': False,
            'is_vr180': False,
            'is_bought': False,
            'subtitles_language': 'en',
            'download_subtitles': False,
            'save_subs_to_kvs': False,
            'prefer_auto_generated_subtitles': False,
            'subtitles_format': 'srt',
        }
        
        config = build_source_config('youtube-channel', cleaned_data)
        
        # Validate URL-specific configuration
        self.assertEqual(config['startUrls'], ['https://youtube.com/channel/UCtest123', 'https://youtube.com/channel/UCtest456'])
        self.assertEqual(config['maxResults'], 1)
        self.assertEqual(config['maxResultsShorts'], 0)
        self.assertEqual(config['maxResultStreams'], 0)
        self.assertEqual(config['sortingOrder'], 'date')
        self.assertEqual(config['dateFilter'], 'month')
        self.assertEqual(config['videoType'], 'video')
        self.assertEqual(config['lengthFilter'], '')
        
        # Validate quality filters
        self.assertTrue(config['qualityFilters']['isHD'])
        self.assertTrue(config['qualityFilters']['hasSubtitles'])
        self.assertFalse(config['qualityFilters']['hasCC'])
        
        # Ensure searchQueries is not set for channel
        self.assertNotIn('searchQueries', config)

    def test_youtube_playlist_config_generation(self):
        """Test YouTube playlist configuration generation"""
        cleaned_data = {
            'source_type': 'youtube-playlist',
            'profile_urls': 'https://youtube.com/playlist?list=PLtest123',
            'max_results': 1,
        }
        
        config = build_source_config('youtube-playlist', cleaned_data)
        
        # Validate playlist-specific configuration
        self.assertEqual(config['startUrls'], ['https://youtube.com/playlist?list=PLtest123'])
        self.assertEqual(config['maxResults'], 1)
        self.assertEqual(config['maxResultsShorts'], 0)
        self.assertEqual(config['maxResultStreams'], 0)

    def test_youtube_hashtag_config_generation(self):
        """Test YouTube hashtag configuration generation"""
        cleaned_data = {
            'source_type': 'youtube-hashtag',
            'profile_urls': 'https://youtube.com/hashtag/python',
            'max_results': 1,
        }
        
        config = build_source_config('youtube-hashtag', cleaned_data)
        
        # Validate hashtag-specific configuration
        self.assertEqual(config['startUrls'], ['https://youtube.com/hashtag/python'])
        self.assertEqual(config['maxResults'], 1)
        self.assertEqual(config['maxResultsShorts'], 0)
        self.assertEqual(config['maxResultStreams'], 0)

    def test_youtube_video_config_generation(self):
        """Test YouTube video configuration generation"""
        cleaned_data = {
            'source_type': 'youtube-video',
            'profile_urls': 'https://youtube.com/watch?v=dQw4w9WgXcQ',
            'max_results': 1,
        }
        
        config = build_source_config('youtube-video', cleaned_data)
        
        # Validate video-specific configuration
        self.assertEqual(config['startUrls'], ['https://youtube.com/watch?v=dQw4w9WgXcQ'])
        self.assertEqual(config['maxResults'], 1)
        self.assertEqual(config['maxResultsShorts'], 0)
        self.assertEqual(config['maxResultStreams'], 0)

    @override_settings(N8N_TEST_SCRAPING_URL='http://localhost:5678/webhook-test/multi-source-scrape')
    @patch('requests.post')
    def test_youtube_search_webhook_trigger(self, mock_post):
        """Test YouTube search webhook triggering with mocked response"""
        # Mock successful webhook response
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {'execution_id': 'test-execution-123'}
        mock_post.return_value = mock_response
        
        # Create run with YouTube search configuration
        run = Run.objects.create(
            user=self.test_user,
            input=json.dumps({
                'sources': [self.youtube_test_configs['youtube-search']],
                'max_results': 1,
                'days_since': 14,
                'auto_infer_columns': True,
                'custom_columns': [],
                'extraction_prompt': "Extract location information, business mentions, contact details, and other relevant data from social media posts. Adapt to the specific platform and content type.",
                'enable_extraction': True
            })
        )
        
        # Trigger the run
        trigger_run(run)
        
        # Verify webhook was called
        mock_post.assert_called_once()
        call_args = mock_post.call_args
        
        # Verify URL (should use test URL)
        self.assertEqual(call_args[0][0], 'http://localhost:5678/webhook-test/multi-source-scrape')
        
        # Verify payload structure
        payload = call_args[1]['json']
        self.assertEqual(payload['maxResults'], 1)
        self.assertEqual(len(payload['sources']), 1)
        
        youtube_source = payload['sources'][0]
        self.assertEqual(youtube_source['platform'], 'youtube')
        self.assertEqual(youtube_source['sourceType'], 'youtube-search')
        self.assertEqual(youtube_source['configuration']['maxResults'], 1)
        self.assertEqual(youtube_source['configuration']['searchQueries'], ['python tutorial'])
        
        # Verify execution ID was saved
        run.refresh_from_db()
        self.assertEqual(run.n8n_execution_id, 'test-execution-123')

    @override_settings(N8N_TEST_SCRAPING_URL='http://localhost:5678/webhook-test/multi-source-scrape')
    @patch('requests.post')
    def test_youtube_channel_webhook_trigger(self, mock_post):
        """Test YouTube channel webhook triggering with mocked response"""
        # Mock successful webhook response
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {'execution_id': 'test-execution-456'}
        mock_post.return_value = mock_response
        
        # Create run with YouTube channel configuration
        run = Run.objects.create(
            user=self.test_user,
            input=json.dumps({
                'sources': [self.youtube_test_configs['youtube-channel']],
                'max_results': 1,
                'days_since': 14,
                'auto_infer_columns': True,
                'custom_columns': [],
                'extraction_prompt': "Extract location information, business mentions, contact details, and other relevant data from social media posts. Adapt to the specific platform and content type.",
                'enable_extraction': True
            })
        )
        
        # Trigger the run
        trigger_run(run)
        
        # Verify webhook was called
        mock_post.assert_called_once()
        call_args = mock_post.call_args
        
        # Verify payload structure
        payload = call_args[1]['json']
        youtube_source = payload['sources'][0]
        self.assertEqual(youtube_source['platform'], 'youtube')
        self.assertEqual(youtube_source['sourceType'], 'youtube-channel')
        self.assertEqual(youtube_source['configuration']['maxResults'], 1)
        self.assertEqual(youtube_source['configuration']['startUrls'], ['https://youtube.com/channel/UCtest123'])

    def test_cost_control_max_results(self):
        """Test that max_results is properly limited for cost control"""
        cleaned_data = {
            'source_type': 'youtube-search',
            'search_queries': 'python tutorial',
            'max_results': 1,  # Explicitly set to 1 for cost control
        }
        
        config = build_source_config('youtube-search', cleaned_data)
        
        # Verify cost control settings
        self.assertEqual(config['maxResults'], 1)
        self.assertEqual(config['maxResultsShorts'], 0)  # No shorts for cost control
        self.assertEqual(config['maxResultStreams'], 0)  # No streams for cost control

    def test_all_youtube_source_types_have_complete_config(self):
        """Test that all YouTube source types have complete configuration"""
        expected_fields = [
            'maxResults', 'maxResultsShorts', 'maxResultStreams',
            'sortingOrder', 'dateFilter', 'videoType', 'lengthFilter',
            'qualityFilters', 'subtitleOptions'
        ]
        
        for source_type in ['youtube-search', 'youtube-channel', 'youtube-playlist', 'youtube-hashtag', 'youtube-video']:
            with self.subTest(source_type=source_type):
                cleaned_data = {
                    'source_type': source_type,
                    'max_results': 1,
                }
                
                # Add required fields for search vs non-search types
                if source_type == 'youtube-search':
                    cleaned_data['search_queries'] = 'python tutorial'
                else:
                    cleaned_data['profile_urls'] = 'https://youtube.com/test'
                
                config = build_source_config(source_type, cleaned_data)
                
                # Check that all expected fields are present
                for field in expected_fields:
                    self.assertIn(field, config, f"Missing field '{field}' for {source_type}")
                
                # Verify cost control
                self.assertEqual(config['maxResults'], 1)
                self.assertEqual(config['maxResultsShorts'], 0)
                self.assertEqual(config['maxResultStreams'], 0)